In [1]:
import os
import pandas as pd

In [20]:
BASE_DIR = os.path.dirname(os.getcwd())
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join(BASE_DIR, 'cache')
os.makedirs(CACHE_DIR, exist_ok=True)

In [3]:
csv_files = [files for files in os.listdir(DATA_DIR) if files.endswith('.csv')]
csv_files

['2005.csv',
 '2006.csv',
 '2007.csv',
 '2008.csv',
 '2009.csv',
 '2010.csv',
 '2011.csv',
 '2012.csv',
 '2013.csv',
 '2014.csv',
 '2015.csv',
 '2016.csv',
 '2017.csv',
 '2018.csv',
 '2019.csv',
 '2020.csv']

In [7]:
filename = '2005.csv'
filepath = os.path.join(DATA_DIR, filename)
temp_df = pd.read_csv(filepath)
temp_df['filename'] = filename
year = filename.replace(".csv", '')
temp_df['year'] = year
temp_df.head(n=10)

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Harry Potter and the Goblet of Fire,"$895,921,036","$290,013,036",32.4%,"$605,908,000",67.6%,2005.csv,2005
1,2,Star Wars: Episode III - Revenge of the Sith,"$868,352,530","$380,270,577",43.8%,"$488,081,953",56.2%,2005.csv,2005
2,3,"The Chronicles of Narnia: The Lion, the Witch ...","$745,013,115","$291,710,957",39.2%,"$453,302,158",60.8%,2005.csv,2005
3,4,War of the Worlds,"$603,873,119","$234,280,354",38.8%,"$369,592,765",61.2%,2005.csv,2005
4,5,King Kong,"$562,363,449","$218,080,025",38.8%,"$344,283,424",61.2%,2005.csv,2005
5,6,Madagascar,"$542,063,846","$193,595,521",35.7%,"$348,468,325",64.3%,2005.csv,2005
6,7,Mr. & Mrs. Smith,"$487,287,646","$186,336,279",38.2%,"$300,951,367",61.8%,2005.csv,2005
7,8,Charlie and the Chocolate Factory,"$474,968,763","$206,459,076",43.5%,"$268,509,687",56.5%,2005.csv,2005
8,9,Mission: Impossible III,"$398,479,497","$134,029,801",33.6%,"$264,449,696",66.4%,2005.csv,2005
9,10,Batman Begins,"$371,853,783","$205,343,774",55.2%,"$166,510,009",44.8%,2005.csv,2005

In [8]:
all_dataframes = []

for filename in csv_files:
    csv_path = os.path.join(DATA_DIR, filename)
    temp_df = pd.read_csv(csv_path)
    temp_df['filename'] = filename
    year = filename.replace(".csv", '')
    temp_df['year'] = year
#     temp_df.head(n=10)
    all_dataframes.append(temp_df)

In [11]:
combined_movie_dataset = pd.concat(all_dataframes)

In [12]:
combined_movie_dataset.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Harry Potter and the Goblet of Fire,"$895,921,036","$290,013,036",32.4%,"$605,908,000",67.6%,2005.csv,2005
1,2,Star Wars: Episode III - Revenge of the Sith,"$868,352,530","$380,270,577",43.8%,"$488,081,953",56.2%,2005.csv,2005
2,3,"The Chronicles of Narnia: The Lion, the Witch ...","$745,013,115","$291,710,957",39.2%,"$453,302,158",60.8%,2005.csv,2005
3,4,War of the Worlds,"$603,873,119","$234,280,354",38.8%,"$369,592,765",61.2%,2005.csv,2005
4,5,King Kong,"$562,363,449","$218,080,025",38.8%,"$344,283,424",61.2%,2005.csv,2005

In [19]:
# jsut making sure that we don't have column names saved for every 
# year's dataframe information in this master combined_movie_dataset
combined_movie_dataset.tail(n=31)

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
686,687,The Portal,$685,-,-,$685,100%,2019.csv,2019
0,1,Bad Boys for Life,"$419,074,646","$204,417,855",48.8%,"$214,656,791",51.2%,2020.csv,2020
1,2,Sonic the Hedgehog,"$306,766,470","$146,066,470",47.6%,"$160,700,000",52.4%,2020.csv,2020
2,3,Dolittle,"$223,343,452","$77,047,065",34.5%,"$146,296,387",65.5%,2020.csv,2020
3,4,Birds of Prey: And the Fantabulous Emancipatio...,"$201,858,461","$84,158,461",41.7%,"$117,700,000",58.3%,2020.csv,2020
4,5,The Invisible Man,"$122,914,050","$64,914,050",52.8%,"$58,000,000",47.2%,2020.csv,2020
5,6,The Gentlemen,"$114,996,853","$36,296,853",31.6%,"$78,700,000",68.4%,2020.csv,2020
6,7,The Call of the Wild,"$107,604,626","$62,342,368",57.9%,"$45,262,258",42.1%,2020.csv,2020
7,8,The Grudge,"$49,511,319","$21,221,803",42.9%,"$28,289,516",57.1%,2020.csv,2020
8,9,Fantasy Island,"$47,315,959","$26,441,782",55.9%,"$20,874,177",44.1%,2020.csv,2020
9,10,Underwater,"$40,882,928","$17,291,078",42.3%,"$23,591,850",57.7%,2020.csv,2020
10,11,Like a Boss,"$29,753,143","$22,169,514",74.5%,"$7,583,629",25.5%,2020.csv,2020
11,12,Bloodshot,"$28,428,855","$10,021,787",35.3%,"$18,407,068",64.7%,2020.csv,2020
12,13,Emma.,"$25,155,355","$10,055,355",40%,"$15,100,000",60%,2020.csv,2020
13,14,Gretel & Hansel,"$21,282,967","$15,347,654",72.1%,"$5,935,313",27.9%,2020.csv,2020
14,15,Brahms: The Boy II,"$20,311,536","$12,611,536",62.1%,"$7,700,000",37.9%,2020.csv,2020
15,16,The Turning,"$18,592,512","$15,472,775",83.2%,"$3,119,737",16.8%,2020.csv,2020
16,17,The Way Back,"$14,690,514","$13,590,514",92.5%,"$1,100,000",7.5%,2020.csv,2020
17,18,La Belle Époque,"$13,225,642",-,-,"$13,225,642",100%,2020.csv,2020
18,19,I Still Believe,"$10,511,001","$9,868,521",93.9%,"$642,480",6.1%,2020.csv,2020
19,20,The Hunt,"$6,512,500","$5,812,500",89.3%,"$700,000",10.7%,2020.csv,2020
20,21,Las Pildoras De Mi Novio,"$6,292,780","$2,971,116",47.2%,"$3,321,664",52.8%,2020.csv,2020
21,22,The Rhythm Section,"$5,989,583","$5,437,971",90.8%,"$551,612",9.2%,2020.csv,2020
22,23,My Spy,"$4,800,750",-,-,"$4,800,750",100%,2020.csv,2020
23,24,The Last Full Measure,"$3,007,863","$2,949,212",98.1%,"$58,651",1.9%,2020.csv,2020
24,25,Trolls World Tour,"$2,792,571",-,-,"$2,792,571",100%,2020.csv,2020
25,26,The Lodge,"$2,681,784","$1,666,564",62.1%,"$1,015,220",37.9%,2020.csv,2020
26,27,Blind Eyes Opened,"$234,505","$234,505",100%,-,-,2020.csv,2020
27,28,Burden,"$139,270","$139,270",100%,-,-,2020.csv,2020
28,29,"14 Days, 12 Nights","$122,806","$122,530",99.8%,$276,0.2%,2020.csv,2020
29,30,First Cow,"$101,068","$101,068",100%,-,-,2020.csv,2020

In [21]:
dataset_path = os.path.join(CACHE_DIR, 'movies-box-office-dataset.csv')
combined_movie_dataset.to_csv(dataset_path, index=False)